-- Auth compatibility for current runtime
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rol" TEXT DEFAULT 'LIDER';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cultoDia" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cultoTurno" INTEGER DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "plan" TEXT DEFAULT 'GENERAL';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pais" TEXT DEFAULT 'AR';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "divisa" TEXT DEFAULT 'ARS';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "idioma" TEXT DEFAULT 'es';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "iglesia" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telefono" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "expira" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "promoCode" TEXT DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "promoDescuento" INTEGER DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "promoMeses" INTEGER DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "promoUsadoAt" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "oauth_provider" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "oauth_id" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "codigoVerif" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "codigoExpira" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "codigoContexto" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pendingPassword" TEXT;

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "refreshToken" TEXT NOT NULL UNIQUE,
  "userAgent" TEXT DEFAULT '',
  "ip" TEXT DEFAULT '',
  "expiresAt" TEXT NOT NULL,
  "revoked" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "user_sessions_userId_idx" ON "user_sessions"("userId");

CREATE TABLE IF NOT EXISTS "promo_codes" (
  "id" SERIAL PRIMARY KEY,
  "code" TEXT NOT NULL UNIQUE,
  "dias_extra" INTEGER NOT NULL DEFAULT 0,
  "tipo" TEXT NOT NULL DEFAULT 'TRIAL_DAYS',
  "descuento_porcentaje" INTEGER NOT NULL DEFAULT 0,
  "duracion_meses" INTEGER NOT NULL DEFAULT 0,
  "max_usos" INTEGER NOT NULL DEFAULT 1,
  "usos" INTEGER NOT NULL DEFAULT 0,
  "activo" INTEGER NOT NULL DEFAULT 1,
  "expiresAt" TEXT,
  "usado" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "promo_codes" ("code","dias_extra","tipo","descuento_porcentaje","duracion_meses","max_usos","usos","activo","usado")
SELECT '15OFF',0,'DISCOUNT',15,3,0,0,1,0
WHERE NOT EXISTS (SELECT 1 FROM "promo_codes" WHERE "code"='15OFF');
