import {
  LayoutDashboard, Bell, Users, UsersRound,
  ClipboardCheck, Calendar, MessageSquare, BarChart2,
  DollarSign, FileSpreadsheet, Sparkles, Settings,
  ShieldCheck, Clock, Ticket, Lock, HandHeart,
  BookOpen, User, Search, Plus, Download,
  Pencil, Trash2, ChevronRight, ChevronDown,
  LogOut, Menu, X, Check, AlertTriangle,
  Info, CheckCircle, XCircle, Heart, MapPin,
  Phone, Mail, Globe, Filter, RefreshCw,
  Upload, Eye, EyeOff, Copy, ExternalLink,
  ArrowLeft, ArrowRight, TrendingUp, TrendingDown,
  Building2, UserPlus, QrCode, Zap, Crown,
  FileText, Send, Archive, ChevronLeft
} from 'lucide-react'

const size = { width: 18, height: 18, strokeWidth: 1.8 }

export const Icons = {
  Dashboard:    (p) => <LayoutDashboard   {...size} {...p} />,
  Premium:      (p) => <Crown             {...size} {...p} />,
  Comunicados:  (p) => <Bell              {...size} {...p} />,
  Users:        (p) => <Users             {...size} {...p} />,
  Groups:       (p) => <UsersRound        {...size} {...p} />,
  Attendance:   (p) => <ClipboardCheck    {...size} {...p} />,
  Calendar:     (p) => <Calendar          {...size} {...p} />,
  Messages:     (p) => <MessageSquare     {...size} {...p} />,
  Reports:      (p) => <BarChart2         {...size} {...p} />,
  Finance:      (p) => <DollarSign        {...size} {...p} />,
  Excel:        (p) => <FileSpreadsheet   {...size} {...p} />,
  AI:           (p) => <Sparkles          {...size} {...p} />,
  Settings:     (p) => <Settings          {...size} {...p} />,
  Shield:       (p) => <ShieldCheck       {...size} {...p} />,
  History:      (p) => <Clock             {...size} {...p} />,
  Ticket:       (p) => <Ticket            {...size} {...p} />,
  CheckIn:      (p) => <Lock              {...size} {...p} />,
  Prayer:       (p) => <HandHeart         {...size} {...p} />,
  Discipleship: (p) => <BookOpen          {...size} {...p} />,
  Profile:      (p) => <User              {...size} {...p} />,
  Search:       (p) => <Search            {...size} {...p} />,
  Plus:         (p) => <Plus              {...size} {...p} />,
  Download:     (p) => <Download          {...size} {...p} />,
  Edit:         (p) => <Pencil            {...size} {...p} />,
  Delete:       (p) => <Trash2            {...size} {...p} />,
  ChevronRight: (p) => <ChevronRight      {...size} {...p} />,
  ChevronDown:  (p) => <ChevronDown       {...size} {...p} />,
  ChevronLeft:  (p) => <ChevronLeft       {...size} {...p} />,
  LogOut:       (p) => <LogOut            {...size} {...p} />,
  Menu:         (p) => <Menu              {...size} {...p} />,
  X:            (p) => <X                {...size} {...p} />,
  Check:        (p) => <Check             {...size} {...p} />,
  AlertTriangle:(p) => <AlertTriangle     {...size} {...p} />,
  Info:         (p) => <Info              {...size} {...p} />,
  CheckCircle:  (p) => <CheckCircle       {...size} {...p} />,
  XCircle:      (p) => <XCircle           {...size} {...p} />,
  Heart:        (p) => <Heart             {...size} {...p} />,
  Phone:        (p) => <Phone             {...size} {...p} />,
  Mail:         (p) => <Mail              {...size} {...p} />,
  Globe:        (p) => <Globe             {...size} {...p} />,
  Filter:       (p) => <Filter            {...size} {...p} />,
  Refresh:      (p) => <RefreshCw         {...size} {...p} />,
  Upload:       (p) => <Upload            {...size} {...p} />,
  Eye:          (p) => <Eye               {...size} {...p} />,
  EyeOff:       (p) => <EyeOff           {...size} {...p} />,
  Copy:         (p) => <Copy              {...size} {...p} />,
  External:     (p) => <ExternalLink      {...size} {...p} />,
  ArrowLeft:    (p) => <ArrowLeft         {...size} {...p} />,
  ArrowRight:   (p) => <ArrowRight        {...size} {...p} />,
  TrendingUp:   (p) => <TrendingUp        {...size} {...p} />,
  TrendingDown: (p) => <TrendingDown      {...size} {...p} />,
  Building:     (p) => <Building2         {...size} {...p} />,
  UserPlus:     (p) => <UserPlus          {...size} {...p} />,
  QrCode:       (p) => <QrCode            {...size} {...p} />,
  Zap:          (p) => <Zap               {...size} {...p} />,
  FileText:     (p) => <FileText          {...size} {...p} />,
  Send:         (p) => <Send              {...size} {...p} />,
  Archive:      (p) => <Archive           {...size} {...p} />,
  MapPin:       (p) => <MapPin            {...size} {...p} />,
}

export default Icons
