import { useEffect, useCallback } from 'react'
import { createPortal } from 'react-dom'

const WIDTHS = { sm: 420, md: 600, lg: 800, xl: 1040, full: null }

export default function Modal({ open, onClose, title, subtitle, size = 'md', children, footer, hideClose = false, danger = false, noPadding = false }) {
  const handleKey = useCallback(e => { if (e.key === 'Escape' && open) onClose?.() }, [open, onClose])
  useEffect(() => { document.addEventListener('keydown', handleKey); return () => document.removeEventListener('keydown', handleKey) }, [handleKey])
  useEffect(() => { if (open) document.body.style.overflow = 'hidden'; else document.body.style.overflow = ''; return () => { document.body.style.overflow = '' } }, [open])
  if (!open) return null
  const w = WIDTHS[size]
  return createPortal((<><style>{`@keyframes cs-modal-in{from{opacity:0;transform:translateY(-12px)scale(.97)}to{opacity:1;transform:translateY(0)scale(1)}}@keyframes cs-overlay-in{from{opacity:0}to{opacity:1}}.cs-modal-close:hover{background:var(--bg-2)!important;color:var(--text)!important}@media(max-width:640px){.cs-modal-box{width:100%!important;max-width:100%!important;max-height:92dvh!important;border-bottom-left-radius:0!important;border-bottom-right-radius:0!important;margin-top:auto!important}.cs-modal-overlay{align-items:flex-end!important}}`}</style><div className="cs-modal-overlay" onClick={e=>{if(e.target===e.currentTarget)onClose?.()}} style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.45)',backdropFilter:'blur(4px)',display:'flex',alignItems:'center',justifyContent:'center',padding:'16px',animationName:'cs-overlay-in',animationDuration:'180ms',animationFillMode:'both'}}><div className="cs-modal-box" role="dialog" aria-modal="true" style={{background:'var(--surface)',borderRadius:'var(--r-2xl,24px)',boxShadow:'var(--shadow-lg)',width:'100%',maxWidth:w?`${w}px`:'95vw',maxHeight:'88dvh',display:'flex',flexDirection:'column',overflow:'hidden',animationName:'cs-modal-in',animationDuration:'220ms',animationFillMode:'both'}}>{(title||!hideClose)&&(<div style={{display:'flex',alignItems:'flex-start',gap:12,padding:'20px 24px 16px',borderBottom:'1px solid var(--border)',flexShrink:0,background:danger?'linear-gradient(135deg,rgba(239,68,68,.06),rgba(239,68,68,.02))':'transparent'}}><div style={{flex:1,minWidth:0}}>{title&&<h2 style={{margin:0,fontSize:17,fontWeight:700,fontFamily:'var(--font-title)',color:danger?'var(--c-error)':'var(--text)',lineHeight:1.3}}>{title}</h2>}{subtitle&&<p style={{margin:'4px 0 0',fontSize:13,color:'var(--text-muted)',lineHeight:1.4}}>{subtitle}</p>}</div>{!hideClose&&(<button className="cs-modal-close" onClick={onClose} style={{flexShrink:0,background:'transparent',border:'1px solid var(--border)',borderRadius:'var(--r-sm,8px)',width:32,height:32,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',color:'var(--text-muted)',fontSize:18,lineHeight:1,transition:'var(--t)',marginTop:-2}}>×</button>)}</div>)}<div style={{flex:1,overflowY:'auto',padding:noPadding?0:'20px 24px',scrollbarWidth:'thin',scrollbarColor:'var(--border-med)transparent'}}>{children}</div>{footer&&<div style={{display:'flex',justifyContent:'flex-end',gap:10,padding:'16px 24px',borderTop:'1px solid var(--border)',flexShrink:0,flexWrap:'wrap'}}>{footer}</div>}</div></div></>), document.body)
}

export function ConfirmModal({open,onClose,onConfirm,title='¿Estás seguro?',message,confirmLabel='Confirmar',cancelLabel='Cancelar',danger=false,loading=false}){return(<Modal open={open} onClose={onClose} title={title} size="sm" danger={danger} footer={<><button className="btn btn-ghost" onClick={onClose} disabled={loading} style={{minWidth:90}}>{cancelLabel}</button><button className={`btn ${danger?'btn-danger':'btn-primary'}`} onClick={onConfirm} disabled={loading} style={{minWidth:90}}>{loading?<span style={{display:'flex',alignItems:'center',gap:6}}><span className="spinner-xs"/>Procesando…</span>:confirmLabel}</button></>}>{message&&<p style={{margin:0,fontSize:14,color:'var(--text-2)',lineHeight:1.6}}>{message}</p>}</Modal>)}
